"""
BURNPIPE_VO_Pipeline -- LORDPIPE-compatible entry point for Pi3X SLAM.

Drop-in replacement for MOD_Pi3X_VisualOdometry's BURNPIPE_VO_Pipeline.py.
Called by LORDPIPE_StreamLine.py (Step 2) as a subprocess::

    python MOD_Pi3X_SLAM/_WegwerfSkript_VO/BURNPIPE_VO_Pipeline.py <step2_vo.yaml>

Accepts the step2_vo.yaml config generated by ``generate_vo_config()`` in
LORDPIPE_StreamLine.py and produces the VO-EPISODING output directory
structure expected by downstream modules (MOD_KabschAnalyzer,
MOD_InterGroupPoseEstimation, etc.).

Output layout::

    VO-EPISODING_{datetime}/
    ├── pipeline_report.json
    └── episode_{name}/
        ├── grouping_manifest.json
        └── _vo_results/run_{datetime}/
            ├── group_000/sparse/0/{cameras,images,points3D}.txt
            ├── group_001/sparse/0/...
            └── ...
"""

import sys
import os
import re
import json
import time
import datetime
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Bootstrap: add module root to sys.path
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent        # _WegwerfSkript_VO/
_MODULE_ROOT = _SCRIPT_DIR.parent                    # Release/ (or MOD_Pi3X_SLAM/)

for p in (str(_MODULE_ROOT), str(_SCRIPT_DIR)):
    if p not in sys.path:
        sys.path.insert(0, p)

import yaml
import numpy as np

from essn_slam import SLAMConfig, Pi3xSLAM
from util_shared_intrinsics import load_shared_intrinsics
from util_colmap import export_per_submap_colmap
from UTIL_IO_Discovery import discover_timestamps, discover_images

logger = logging.getLogger("BURNPIPE_VO_Pipeline")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
)

IMAGE_EXTS = {'.jpg', '.jpeg', '.png', '.bmp'}
EPISODE_RE = re.compile(r'^episode_\d+')
UNDISTORT_RE = re.compile(r'^undistort_fov')


# ============================================================================
# Config loading
# ============================================================================

def load_vo_config(yaml_path: str) -> Dict[str, Any]:
    """Load step2_vo.yaml and return the raw config dict."""
    with open(yaml_path, 'r') as f:
        cfg = yaml.safe_load(f)
    return cfg


def _parse_cameras(input_cfg: dict) -> Tuple[List[str], Dict[str, List[str]]]:
    """Parse the VO-style cameras config into SLAM-style cameras + angles.

    VO config formats:
      A) cameras: {cam0: "p+0_y+30_r+0", cam1: "p+0_y-30_r+0"}
         Each camera → single orientation string.
      B) cameras: ["cam0", "cam1"]  (already SLAM-style)
         Optional camera_angles: {cam0: [...], cam1: [...]}

    Returns:
        (camera_list, camera_angles_dict)
    """
    raw = input_cfg.get('cameras', {})

    if isinstance(raw, dict):
        cameras = sorted(raw.keys())
        camera_angles = {cam: [raw[cam]] for cam in cameras}
    elif isinstance(raw, list):
        cameras = list(raw)
        camera_angles = input_cfg.get('camera_angles', {})
    else:
        cameras = ['cam0']
        camera_angles = {}

    return cameras, camera_angles


# ============================================================================
# Episode / image discovery
# ============================================================================

def _discover_episodes(input_base: Path, episode_filter: Optional[list] = None) -> List[Path]:
    """Find episode directories under the EPISODING root."""
    episodes = sorted([
        d for d in input_base.iterdir()
        if d.is_dir() and EPISODE_RE.match(d.name)
    ])
    if episode_filter:
        episodes = [e for e in episodes if e.name in episode_filter]
    if not episodes:
        logger.warning("No episode directories found in %s", input_base)
    return episodes


def _find_undistort_dir(episode_dir: Path) -> Optional[Path]:
    """Find the undistort_fov* directory inside an episode."""
    for d in sorted(episode_dir.iterdir()):
        if d.is_dir() and UNDISTORT_RE.match(d.name):
            return d
    return episode_dir


def _discover_episode_images(
    image_root: Path,
    cameras: List[str],
    camera_angles: Dict[str, List[str]],
    stride: int = 1,
) -> Tuple[Optional[list], list, bool]:
    """Discover images for an episode, trying multi-view then flat.

    Returns:
        (timestamps_or_None, view_keys_or_flat_paths, is_multi_view)
    """
    try:
        timestamps, view_keys = discover_timestamps(
            data_root=str(image_root),
            cameras=cameras,
            camera_angles=camera_angles,
            stride=stride,
        )
        return timestamps, view_keys, True
    except ValueError:
        pass

    try:
        flat_paths = discover_images(
            data_root=str(image_root),
            cameras=cameras,
            camera_angles=camera_angles,
            stride=stride,
        )
        return None, flat_paths, False
    except ValueError:
        pass

    logger.error("No images found in %s", image_root)
    return None, [], False


# ============================================================================
# Output directory creation
# ============================================================================

def _create_vo_output_dir(input_base: Path, output_base: Optional[str]) -> Path:
    """Create VO-EPISODING_{datetime}/ output directory.

    When output_base is None, creates a sibling of the EPISODING directory.
    """
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    if output_base:
        vo_dir = Path(output_base)
    else:
        parent = input_base.parent
        vo_dir = parent / f"VO-EPISODING_{ts}"
    vo_dir.mkdir(parents=True, exist_ok=True)
    return vo_dir


def _create_episode_output(vo_output_dir: Path, episode_name: str) -> Tuple[Path, Path]:
    """Create per-episode output directories.

    Returns:
        (episode_dir, vo_results_dir)
    """
    run_ts = datetime.datetime.now().strftime("run_%Y%m%d_%H%M%S")
    episode_dir = vo_output_dir / episode_name
    vo_results_dir = episode_dir / "_vo_results" / run_ts
    vo_results_dir.mkdir(parents=True, exist_ok=True)
    return episode_dir, vo_results_dir


# ============================================================================
# Config translation: step2_vo.yaml -> SLAMConfig
# ============================================================================

def _build_slam_config(
    vo_cfg: Dict[str, Any],
    vo_results_dir: Path,
    shared_K: Optional[np.ndarray],
    shared_K_hw: Optional[Tuple[int, int]],
) -> SLAMConfig:
    """Translate VO pipeline config into SLAMConfig."""
    paths = vo_cfg.get('paths', {})
    grouping = vo_cfg.get('grouping', {})
    model = vo_cfg.get('model', {})
    processing = vo_cfg.get('processing', {})
    slam_features = vo_cfg.get('slam_features', {})

    group_size = grouping.get('group_size', 20)
    overlap = grouping.get('overlap_frames', 5)

    device = model.get('device', 'cuda')
    dtype = model.get('dtype', 'float16')

    pixel_limit = processing.get('pixel_limit', 255000)
    conf_threshold = processing.get('conf_threshold', 0.5)
    if conf_threshold < 1.0:
        conf_threshold = conf_threshold * 100.0

    use_kf = slam_features.get('keyframe_selection', True)
    use_lc = slam_features.get('loop_closure', True)
    use_viewer = slam_features.get('viewer', False)

    return SLAMConfig(
        ckpt_path=paths.get('ckpt_path', ''),
        device=device,
        dtype=dtype,
        pixel_limit=pixel_limit,
        submap_size=group_size,
        overlap_window=overlap,
        max_submaps=0,
        conf_threshold=conf_threshold,
        conf_min_abs=0.0,
        keyframe_method='lk',
        use_keyframe_selection=use_kf,
        min_disparity=50.0,
        max_loops=1 if use_lc else 0,
        lc_retrieval_threshold=0.95,
        lc_conf_threshold=0.25,
        sim3_inlier_thresh=0.5,
        viewer_port=8080,
        viewer_max_points=0,
        output_dir=str(vo_results_dir),
        shared_intrinsics=shared_K,
        shared_intrinsics_hw=shared_K_hw,
    )


# ============================================================================
# Grouping manifest + pipeline report
# ============================================================================

def _write_grouping_manifest(
    episode_dir: Path,
    exported_groups: list,
    image_paths: list,
    group_size: int,
    overlap: int,
):
    """Write grouping_manifest.json for an episode."""
    groups = []
    for group_idx, group_dir in exported_groups:
        groups.append({
            "group_name": f"group_{group_idx:03d}",
            "group_dir": str(group_dir),
            "group_size": group_size,
        })

    manifest = {
        "total_images": len(image_paths),
        "group_size": group_size,
        "overlap_frames": overlap,
        "num_groups": len(groups),
        "groups": groups,
    }
    manifest_path = episode_dir / "grouping_manifest.json"
    with open(manifest_path, 'w') as f:
        json.dump(manifest, f, indent=2)
    logger.info("Wrote %s", manifest_path)


def _write_pipeline_report(
    vo_output_dir: Path,
    episodes_processed: list,
    total_time: float,
    vo_cfg: Dict[str, Any],
    shared_K_loaded: bool,
):
    """Write pipeline_report.json at the VO-EPISODING root."""
    report = {
        "module": "MOD_Pi3X_SLAM",
        "backend": "pi3x_slam",
        "timestamp": datetime.datetime.now().isoformat(),
        "total_time_s": total_time,
        "episodes_processed": len(episodes_processed),
        "episodes": episodes_processed,
        "shared_intrinsics": {
            "enabled": vo_cfg.get('shared_intrinsics', {}).get('enabled', False),
            "loaded": shared_K_loaded,
        },
        "slam_features": {
            "keyframe_selection": True,
            "loop_closure": True,
            "pose_graph_optimization": True,
        },
        "config_snapshot": {k: v for k, v in vo_cfg.items()
                           if k != 'shared_intrinsics'},
    }
    report_path = vo_output_dir / "pipeline_report.json"
    with open(report_path, 'w') as f:
        json.dump(report, f, indent=2, default=str)
    logger.info("Wrote %s", report_path)


# ============================================================================
# Main pipeline
# ============================================================================

def run_pipeline(config_path: str) -> int:
    """Run the full VO pipeline via Pi3X SLAM.

    Args:
        config_path: Path to step2_vo.yaml.

    Returns:
        Exit code (0 = success).
    """
    t_start = time.time()

    # 1. Load config
    logger.info("Loading VO config from %s", config_path)
    vo_cfg = load_vo_config(config_path)
    paths_cfg = vo_cfg.get('paths', {})
    input_base = Path(paths_cfg['input_base'])
    grouping = vo_cfg.get('grouping', {})
    input_cfg = vo_cfg.get('input', {})
    filters_cfg = vo_cfg.get('filters', {})

    cameras, camera_angles = _parse_cameras(input_cfg)
    stride = input_cfg.get('stride_frame', 1)
    group_size = grouping.get('group_size', 20)
    overlap = grouping.get('overlap_frames', 5)

    logger.info("Input base: %s", input_base)
    logger.info("Cameras: %s", cameras)
    logger.info("Group size: %d, overlap: %d, stride: %d", group_size, overlap, stride)

    # 2. Load shared intrinsics
    si_cfg = vo_cfg.get('shared_intrinsics', {})
    shared_K = None
    shared_K_hw = None
    if si_cfg.get('enabled', False):
        shared_K = load_shared_intrinsics(
            input_base=input_base,
            source=si_cfg.get('source', 'auto'),
            explicit_path=si_cfg.get('path'),
        )
        if shared_K is not None:
            yaml_path = input_base / "undistorted_intrinsics.yaml"
            if yaml_path.is_file():
                with open(yaml_path) as f:
                    intr_data = yaml.safe_load(f)
                shared_K_hw = (
                    int(intr_data.get('image_height', 0)),
                    int(intr_data.get('image_width', 0)),
                )
            logger.info("Shared K loaded, original_hw=%s", shared_K_hw)
        else:
            logger.warning(
                "shared_intrinsics.enabled=true but file not found; "
                "falling back to estimated intrinsics"
            )

    # 3. Create output directory
    vo_output_dir = _create_vo_output_dir(
        input_base, paths_cfg.get('output_base'))
    logger.info("Output: %s", vo_output_dir)

    # 4. Discover episodes
    episodes = _discover_episodes(input_base, filters_cfg.get('episodes'))
    if not episodes:
        logger.info("No episode dirs found; treating input_base as a single episode")
        episodes = [input_base]

    episodes_processed = []

    # 5. Process each episode
    for episode_dir in episodes:
        episode_name = episode_dir.name
        logger.info("=" * 60)
        logger.info("Processing episode: %s", episode_name)

        # 5a. Find image directory
        image_root = _find_undistort_dir(episode_dir)
        logger.info("Image root: %s", image_root)

        # 5b. Discover images
        timestamps, view_keys_or_paths, is_multi_view = \
            _discover_episode_images(image_root, cameras, camera_angles, stride)

        if is_multi_view:
            n_images = sum(len(ts) for ts in timestamps)
            logger.info("Found %d timestamps, %d total images (multi-view)",
                        len(timestamps), n_images)
        else:
            if not view_keys_or_paths:
                logger.warning("No images found for episode %s, skipping", episode_name)
                continue
            n_images = len(view_keys_or_paths)
            logger.info("Found %d images (flat)", n_images)

        # 5c. Create output directories
        episode_out, vo_results_dir = _create_episode_output(
            vo_output_dir, episode_name)

        # 5d. Build SLAM config
        slam_config = _build_slam_config(
            vo_cfg, vo_results_dir, shared_K, shared_K_hw)

        # 5e. Run Pi3X SLAM
        logger.info("Running Pi3X SLAM...")
        view_keys = view_keys_or_paths if is_multi_view else []
        slam = Pi3xSLAM(slam_config, view_keys=view_keys)

        if is_multi_view:
            slam.run_timestamps(timestamps)
        else:
            slam.run(view_keys_or_paths)

        # 5f. Export per-group COLMAP (VO-EPISODING format)
        logger.info("Exporting per-group COLMAP models...")
        sp = slam.submap_processor
        exported_groups = export_per_submap_colmap(
            str(vo_results_dir), sp.map, sp.graph, shared_K=shared_K)
        logger.info("Exported %d groups", len(exported_groups))

        # 5g. Write grouping manifest
        all_paths = []
        if is_multi_view:
            for ts in timestamps:
                all_paths.extend(ts.values())
        else:
            all_paths = view_keys_or_paths
        _write_grouping_manifest(
            episode_out, exported_groups, all_paths, group_size, overlap)

        episodes_processed.append({
            "name": episode_name,
            "num_images": n_images,
            "num_groups": len(exported_groups),
            "num_submaps": sp.map.get_num_submaps(),
            "num_loop_closures": sp.graph.get_num_loops(),
        })

    # 6. Write pipeline report
    total_time = time.time() - t_start
    _write_pipeline_report(
        vo_output_dir, episodes_processed, total_time,
        vo_cfg, shared_K is not None)

    logger.info("=" * 60)
    logger.info("Pi3X SLAM VO pipeline complete in %.1fs", total_time)
    logger.info("  Episodes: %d", len(episodes_processed))
    logger.info("  Output: %s", vo_output_dir)
    logger.info("=" * 60)

    return 0


# ============================================================================
# Entry point
# ============================================================================

def main():
    if len(sys.argv) < 2:
        print("Usage: python BURNPIPE_VO_Pipeline.py <step2_vo.yaml>")
        sys.exit(1)

    config_path = sys.argv[1]
    if not os.path.isabs(config_path):
        config_path = os.path.join(os.getcwd(), config_path)

    if not os.path.isfile(config_path):
        print(f"Config file not found: {config_path}")
        sys.exit(1)

    exit_code = run_pipeline(config_path)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
